/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clubfootball;

import java.awt.BorderLayout;
import java.awt.Container;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JToolBar;
import java.sql.*;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
/**
 *
 * @author JaBeD
 */
public class TeamPage extends javax.swing.JFrame {

    /**
     * Creates new form TeamPage
     */
   
    public TeamPage() {
        initComponents();
       
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SquadBtn = new javax.swing.JButton();
        JerseyBtn = new javax.swing.JButton();
        JerseyBtn.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		String connectionUrl = "jdbc:sqlserver://localhost:1433;" +
        				"databaseName=Club Football DBMS;integratedSecurity=true;";

        			// Declare the JDBC objects.
        			Connection con = null;
        			Statement stmt = null;
        			ResultSet rs = null;
        			
        	        	try {
        	        		// Establish the connection.
        	        		Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        	            		con = DriverManager.getConnection(connectionUrl);
        	            
        	            		// Create and execute an SQL statement that returns some data.
        	            		 
        	            				
        	            	
        	            		String SQL ="select Player.Player_Name,Player.Jersey_No"
            	            				+ "from Player  "
            	            				+ "where Player.Team ='Arsenal FC'";
        	                       
        	            			
        	            		stmt = con.createStatement();
            	            	rs = stmt.executeQuery(SQL);
        	            		
        	            		
            	            	//where Team='"+TeamComboBox.getSelectedItem()+"'
      
        	            
        	            
        	            		// Iterate through the data in the result set and display it.
        	            		
        	            		//System.out.println(TeamComboBox.getSelectedItem()+" Squad" +"\n");
        	            		while (rs.next()) {  	     
        	            	  	     
        	            			
        	            			System.out.println("Player Name" + "\t\t" + rs.getString("Player_Name"));        	            			
         	            			System.out.println("Jersey No" + "\t\t" + rs.getInt("Jersey_No"));        	            		 
        	            			System.out.println("\n");
        	            			
        	            			ShowTextArea.append("Player Name" + "\t\t" +rs.getString ("Player_Name") 
        	            			 + "Jersey No" + "\t\t" + rs.getInt("Jersey_No"));
        	            			
        	      
        	            			
        	            		}
        	            	
        	        	}
        	        
        			// Handle any errors that may have occurred.
        			catch (Exception e) {
        				e.printStackTrace();
        			}

        			finally {
        				if (rs != null) try { rs.close(); } catch(Exception e) {}
        		    		if (stmt != null) try { stmt.close(); } catch(Exception e) {}
        		    		if (con != null) try { con.close(); } catch(Exception e) {}
        			}
        		
        	}
        });
        
        
        PositionBtn = new javax.swing.JButton();
        PositionBtn.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		String connectionUrl = "jdbc:sqlserver://localhost:1433;" +
        				"databaseName=Club Football DBMS;integratedSecurity=true;";

        			// Declare the JDBC objects.
        			Connection con = null;
        			Statement stmt = null;
        			ResultSet rs = null;
        			
        	        	try {
        	        		// Establish the connection.
        	        		Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        	            		con = DriverManager.getConnection(connectionUrl);
        	            
        	            		// Create and execute an SQL statement that returns some data.
        	            		 
        	            				
        	            	
        	            		String SQL ="select Player.Player_Name,Player.Position"
            	            				+ "from Player  "
            	            				+ "where Player.Team ='Arsenal FC'";
        	                       
        	            			
        	            		stmt = con.createStatement();
            	            	rs = stmt.executeQuery(SQL);
        	            		
        	            		
            	            	//where Team='"+TeamComboBox.getSelectedItem()+"'
      
        	            
        	            
        	            		// Iterate through the data in the result set and display it.
        	            		
        	            		//System.out.println(TeamComboBox.getSelectedItem()+" Squad" +"\n");
        	            		while (rs.next()) {  	     
        	            	  	     
        	            			
        	            			System.out.println("Player Name" + "\t\t" + rs.getString("Player_Name"));        	            			
         	            			System.out.println("Position" + "\t\t" + rs.getInt("Position"));        	            		 
        	            			System.out.println("\n");
        	            			
        	            			ShowTextArea.append("Player Name" + "\t\t" +rs.getString ("Player_Name") 
        	            			 + "Position" + "\t\t" + rs.getString("Position"));
        	            			
        	      
        	            			
        	            		}
        	            	
        	        	}
        	        
        			// Handle any errors that may have occurred.
        			catch (Exception e) {
        				e.printStackTrace();
        			}

        			finally {
        				if (rs != null) try { rs.close(); } catch(Exception e) {}
        		    		if (stmt != null) try { stmt.close(); } catch(Exception e) {}
        		    		if (con != null) try { con.close(); } catch(Exception e) {}
        			}
        		
        	}
        		
        	
        });
        NationalityBtn = new javax.swing.JButton();
        TeamComboBox = new javax.swing.JComboBox<>();
        EnterPlayerLabel = new javax.swing.JLabel();
        EnterBtn = new javax.swing.JButton();
        InputJTextField = new javax.swing.JTextField();
        BackBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShowTextArea = new javax.swing.JTextArea();
        ShowTextArea.setEditable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SquadBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SquadBtn.setText("Squad");
        SquadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquadBtnActionPerformed(evt);
            }
        });

        JerseyBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JerseyBtn.setText("Jersey");

        PositionBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PositionBtn.setText("Position");

        NationalityBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        NationalityBtn.setText("Nationality");

        TeamComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arsenal FC", "Manchester City", "Manchester United", "Chelsea", "Liverpool" }));
        TeamComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamComboBoxActionPerformed(evt);
            }
        });

        EnterPlayerLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EnterPlayerLabel.setText("Enter players name");

        EnterBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EnterBtn.setText("Enter");

        InputJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputJTextFieldActionPerformed(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackBtn.setText("back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        ShowTextArea.setColumns(20);
        ShowTextArea.setRows(5);
        jScrollPane1.setViewportView(ShowTextArea);
        
        JPanel panel = new JPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(63)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(TeamComboBox, GroupLayout.PREFERRED_SIZE, 154, GroupLayout.PREFERRED_SIZE)
        					.addGap(207)
        					.addComponent(SquadBtn, GroupLayout.PREFERRED_SIZE, 131, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 73, Short.MAX_VALUE))
        				.addComponent(PositionBtn, GroupLayout.PREFERRED_SIZE, 131, GroupLayout.PREFERRED_SIZE))
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(71)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(NationalityBtn)
        						.addComponent(JerseyBtn, GroupLayout.PREFERRED_SIZE, 131, GroupLayout.PREFERRED_SIZE))
        					.addContainerGap(289, Short.MAX_VALUE))
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
        					.addComponent(BackBtn, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE)
        					.addGap(77))))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(31)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(EnterPlayerLabel, GroupLayout.PREFERRED_SIZE, 326, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 1068, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(InputJTextField, GroupLayout.PREFERRED_SIZE, 396, GroupLayout.PREFERRED_SIZE)
        					.addGap(249)
        					.addComponent(EnterBtn, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(43)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(TeamComboBox, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        						.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        							.addComponent(SquadBtn, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        							.addComponent(JerseyBtn, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE))))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(57)
        					.addComponent(panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(15)
        					.addComponent(BackBtn, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(PositionBtn, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        				.addComponent(NationalityBtn, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
        			.addGap(43)
        			.addComponent(EnterPlayerLabel, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(InputJTextField, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
        				.addComponent(EnterBtn, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(371))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 377, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())))
        );
        getContentPane().setLayout(layout);

        pack();
    }
    
    
    /* action listener of squad button */
    private void SquadBtnActionPerformed(java.awt.event.ActionEvent evt) {
    	// Create a variable for the connection string.
    	       //int selectedOption=TeamComboBox.getSelectedItem();
    	        
    			String connectionUrl = "jdbc:sqlserver://localhost:1433;" +
    				"databaseName=Club Football DBMS;integratedSecurity=true;";

    			// Declare the JDBC objects.
    			Connection con = null;
    			Statement stmt = null;
    			ResultSet rs = null;
    			
    	        	try {
    	        		// Establish the connection.
    	        		Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
    	            		con = DriverManager.getConnection(connectionUrl);
    	            
    	            		// Create and execute an SQL statement that returns some data.
    	            		 
    	            				
    	            	
    	            		String SQL ="select Player_Name,Jersey_No,Position,National_Team,Age "
        	            				+ "from Player  "
        	            				+ "where Team='"+TeamComboBox.getSelectedItem()+"'";
    	                       
    	            			
    	            		stmt = con.createStatement();
        	            	rs = stmt.executeQuery(SQL);
    	            		
    	            		
    	            		
  
    	            
    	            
    	            		// Iterate through the data in the result set and display it.
    	            		
    	            		System.out.println(TeamComboBox.getSelectedItem()+" Squad" +"\n");
    	            		while (rs.next()) {  	     
    	            	  	     
    	            			
    	            			System.out.println("Player Name" + "\t\t" + rs.getString("Player_Name"));
    	            			System.out.println("Age" + "\t\t\t" + rs.getInt("Age"));
    	            			System.out.println("Jersey No" + "\t\t" + rs.getInt("Jersey_No"));
    	            			System.out.println("Postion" + "\t\t\t" + rs.getString("Position"));
    	            			System.out.println("National Team"+ "\t\t" + rs.getString("National_Team")); 
    	            			System.out.println("\n");
    	            			
    	            			ShowTextArea.append("Player Name" + "\t\t" +rs.getString ("Player_Name") + "\n"+ "Age" + "\t\t" + rs.getInt("Age")+"\n"
    	            			 + "Jersey No" + "\t\t" + rs.getInt("Jersey_No") +"\n"+"Postion" + "\t\t" + rs.getString("Position") +"\n"+
    	            			 "National Team"+ "\t\t" + rs.getString("National_Team") + "\n\n");
    	            			
    	      
    	            			
    	            		}
    	            	
    	        	}
    	        
    			// Handle any errors that may have occurred.
    			catch (Exception e) {
    				e.printStackTrace();
    			}

    			finally {
    				if (rs != null) try { rs.close(); } catch(Exception e) {}
    		    		if (stmt != null) try { stmt.close(); } catch(Exception e) {}
    		    		if (con != null) try { con.close(); } catch(Exception e) {}
    			}
        
    }

    private void TeamComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamComboBoxActionPerformed

    private void InputJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputJTextFieldActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
          new SelectionPage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackBtnActionPerformed
   
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeamPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         new TeamPage(); 
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton EnterBtn;
    private javax.swing.JLabel EnterPlayerLabel;
    private javax.swing.JTextField InputJTextField;
    private javax.swing.JButton JerseyBtn;
    private javax.swing.JButton NationalityBtn;
    private javax.swing.JButton PositionBtn;
    private javax.swing.JTextArea ShowTextArea;
    private javax.swing.JButton SquadBtn;
    private javax.swing.JComboBox<String> TeamComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
}
